Add Annex F: History, Motivation and Rational
spdx/spdx-spec pull request #1008
Opened 2024-07-25 12:06 UTC by bact

- Using text and 4 figures from Bob's Word doc 2024-07-04

### Notes
- SPDX is stylized as "Software Package Data e*X*change" and "System Package Data e*X*change" in this annex (same as in the new Introduction, as the last two paragraphs of this annex are largely similar to the Intro).
  - While in other instances of the spec, they are written as "Software Package Data Exchange" and "System Package Data Exchange".
  - Do we like to change both of them to a regular spelling?
- Links. These two links at the end of the doc may need an update for 3.0.1:
  > The SPDX 3.0 ontology is available at:
  > https://github.com/spdx/spdx-spec/tree/development/v3.0/ontology
  >
  > The SPDX 3.0 specification is available as web pages at:
  > https://spdx.github.io/spdx-spec/v3.0/

2024-07-29 00:32 UTC, bobmartin3000 approved these changes
LGTM

2024-08-05 09:59 UTC, bact commented
Note the links to model, ontology, and spec at Lines 136-143. These may need to recheck before publication.

2024-08-09 18:44 UTC, kestewart commented on docs/histroy.md
> +version in 2016. The 2.1 version of SPDX was published through the Linux
```suggestion
version in 2016.   The 2.2 version of the specification was published in 2020 to address the required SBOM minimum elements.   The 2.2.1 version of SPDX specification was published through the Linux
```

2024-08-09 18:51 UTC, goneall requested changes
Since this is the history from an ISO perspective, we should start with SPDX history going back to 1.0 then, more importantly, through the previous ISO submission then adding this additional information.

I wonder if this chapter is even needed for the ISO submission since our prior submission did not include this level of detail.  If it isn't required, I would recommend removing it.

2024-08-09 18:54 UTC, goneall commented
> Since this is the history from an ISO perspective, we should start with SPDX history going back to 1.0 then, more importantly, through the previous ISO submission then adding this additional information.
> 
> I wonder if this chapter is even needed for the ISO submission since our prior submission did not include this level of detail. If it isn't required, I would recommend removing it.

In reading further, it looks like the SPDX history is there, but much later in the document.  Perhaps reordering the history to start more at the beginning may fix the problem.

2024-08-10 17:17 UTC, kestewart commented
Met with @bact, @goneall and decided this needs to be redone/renumbered, and depends on #992 being applied first.   

Discussion is this isn't essential for the .pdf, and can be handled in a cover letter to OMG with the .pdf;  and if we want to include it for ISO submission; probably needs to be reworked as described above.

2024-08-10 17:18 UTC, kestewart requested changes
No longer Annex F (if we end up including).  Needs discussion.

2024-08-10 17:18 UTC, goneall commented
Also note that the annex numbering needs to change and the mkdocs.yaml file needs to be updated.

2024-08-11 20:50 UTC, kestewart commented
I'm fine with this going to OMG.   This needs the Annex F references updated.

2024-08-11 21:33 UTC, kestewart commented on docs/history.md
> +# Annex F: History, Motivation and Rational (Informative)
```suggestion
#History with OMG, Motivation and Rational (Informative)
```

2024-08-11 21:36 UTC, kestewart approved these changes
Approve this as long as added to mkdocs

2024-08-11 21:37 UTC, goneall approved these changes
LGTM

2024-08-11 21:45 UTC, bact commented
Please use https://github.com/spdx/spdx-spec/pull/1053 instead

2024-08-12 00:49 UTC, closed without merging