Fix strikethrough and typo in relationshipType translation table (Annex A)
spdx/spdx-spec pull request #1017
Opened 2024-07-31 13:57 UTC by bact

- Replace strikethrough formatting with italic
- Fix typo: hasPrequisite -> hasPrerequisite

### Question
- What is "lifecycle scope" in the last column?
  - Other values in this column are types in LifecycleScopeType (for example, "build", "build, runtime", "test") or a string stating "various LifecycleScopeType".
- Should this "lifecycle scope" string be replaced by "various LifecycleScopeType"?

2024-08-04 11:57 UTC, zvr requested changes
I don't see a point in changing the typography for relationship names, since the second column clearly says they were removed.

2024-08-04 11:57 UTC, zvr commented on docs/annexes/diffs-from-previous-editions.md
> +| *DEPENDENCY_OF* | [removed] | | |
```suggestion
| DEPENDENCY_OF | [removed] | | |
```

2024-08-04 11:57 UTC, zvr commented on docs/annexes/diffs-from-previous-editions.md
> +| *DESCRIBED_BY* | [removed] | | |
```suggestion
| DESCRIBED_BY | [removed] | | |
```

2024-08-04 11:57 UTC, zvr commented on docs/annexes/diffs-from-previous-editions.md
> +| *PATCH_FOR* | [removed] | | |
```suggestion
| PATCH_FOR | [removed] | | |
```

2024-08-04 11:57 UTC, zvr commented on docs/annexes/diffs-from-previous-editions.md
> +| *PREREQUISITE_FOR* | [removed] | | |
```suggestion
| PREREQUISITE_FOR | [removed] | | |
```

2024-08-05 15:24 UTC, bact commented
Close this one as it will be better covered by #1019

2024-08-05 15:24 UTC, closed without merging