Additional migration documentation for relationship types
spdx/spdx-spec pull request #1019
Opened 2024-08-04 21:29 UTC by goneall

Rather than removing support for the SPDX 2.X relationships, it looks like we can just reverse the direction and use one of the SPDX 3.X relationship types.

I also found one or two relationship types that was not documented.

2024-08-05 09:26 UTC, bact commented
@goneall do you mind to fix typo hasPrequisite / hasPrerequisite typo at line 242 please?  So we can close #1017 and use this PR instead.

2024-08-05 15:05 UTC, goneall commented
> It looks the direction column is not complete as well (not your PR but the existing one). I will just copied my comments from [#1017 (comment)](https://github.com/spdx/spdx-spec/pull/1017#issue-2440131935)
> 
> ### Questions
> 1. Does this table complete?
>    
>    * A sentence before the table said:
>      > Relationship migration is being worked out in the relationships spreadsheet. Once completed, the following table will reflect the translation for relationship types from SPDX 2.3 to SPDX 3.0:
> 2. What does "lifecycle scope" in the last column mean?
>    
>    * Other values in this column are types in LifecycleScopeType (for example, "build", "build, runtime", "test") or a string stating "various LifecycleScopeType".
>    * Should this "lifecycle scope" string be replaced by "various LifecycleScopeType"?
> 3. The 3rd column ("Swap to and from?") probably not complete?
>    
>    * For example, 2.3 `DATA_FILE_OF` and 3.0 `hasDataFile` they are swapped in direction. But there's no "Y" marked in their column.
>    * A (is a) `DATA_FILE_OF` B
>    * B `hasDataFile` A

We should fix these as well - I won't have time to go through another pass before my trip - perhaps we can open a separate PR for the remaining questions.

Ping @kestewart

2024-08-05 15:22 UTC, bact approved these changes

2024-08-05 15:23 UTC, bact commented
> We should fix these as well - I won't have time to go through another pass before my trip - perhaps we can open a separate PR for the remaining questions.

Agree. Let's merge this first and manage other stuff in another PR.

2024-08-05 18:22 UTC, bact commented
I have open PR #1022, as a patch to @goneall's branch, to add all missing directions, fix typos in descendantOf and hasVariant names, and address all the three questions above.

2024-08-06 06:01 UTC, bact requested changes

2024-08-06 06:01 UTC, bact commented on docs/annexes/diffs-from-previous-editions.md
> +| TEST_OF | hasTest | Y | lifecycle scope |
```suggestion
| TEST_OF | hasTest | Y | various lifecycle scope |
```

I missed one here.

2024-08-06 16:40 UTC, JPEWdev approved these changes

2024-08-06 17:18 UTC, bact requested changes

2024-08-06 17:18 UTC, bact commented on docs/annexes/diffs-from-previous-editions.md
> +| TEST_OF | hasTest | Y | lifecycle scope |
@kestewart the other lifecycle-scoped rows in the table are already using this "various lifecycle scope" text.
This suggested change is to keep line 258 consistent with other rows.

2024-08-06 17:19 UTC, bact commented on docs/annexes/diffs-from-previous-editions.md
> +| TEST_OF | hasTest | Y | lifecycle scope |
@kestewart the other lifecycle-scope rows in the table already use the text "various lifecycle scope".

This suggested change is to keep Line 258 consistent with those other rows.

2024-08-07 14:34 UTC, kestewart approved these changes
Thanks for the cleanup and making things more consistent.

2024-08-08 16:26 UTC, zvr approved these changes

2024-08-08 16:26 UTC, merged

2024-09-05 09:40 UTC, bact commented
To future readers, this doc is no longer in this repo and is now available at https://github.com/spdx/using/