Add Legacy Text Template format section back to the Matching Guidelines
spdx/spdx-spec pull request #1026
Opened 2024-08-06 15:57 UTC by bact

standardLicenseTemplate and standardAdditionTemplate still need the Legacy Text Template.

See discussion in https://github.com/spdx/spdx-3-model/issues/747#issuecomment-2263453540

- Use source from https://github.com/spdx/spdx-spec/blob/development/v2.3.1/chapters/license-matching-guidelines-and-templates.md (v2.3.1 dev)
- Adjusted anchor numbering, links
- Add missing anchors: C.6.4

2024-08-06 16:13 UTC, maxhbr approved these changes
LGTM, easy to review in the rich diff

2024-08-07 14:40 UTC, kestewart commented
@jlovejoy, @swinslow - here's the PR that is adding it back, that was referenced yesterday.

2024-08-07 14:57 UTC, zvr requested changes
The source where we copy the whole annex should be https://github.com/spdx/license-list-XML/blob/main/DOCS/license-matching-guidelines-and-templates.md and not some ancient version from SPDXv2.

2024-08-07 16:09 UTC, bact commented
@zvr Thank you for the pointer to upstream one at license-list-XML repo. I was using v2.3.1 only because it's the latest version before v3.0 (which doesn't has this file). 

I just have checked the Legacy Text Template format section from both sources (license-list-XML and v2.3.1), they are identical.

2024-08-07 18:50 UTC, zvr commented
@bact have you checked that the complete file is identical (not only the last section) ?

2024-08-07 19:05 UTC, bact commented
@zvr this PR is based on the existing file. The last section is added. Other sections are added by PR #968.

I haven't look very carefully all of them, only headings (that's how I spotted the missing "C.6.4"). I can check them all again.

2024-08-07 20:01 UTC, bact commented
Done. Every sections in the source of license-list-XML and v2.3.1 are identical.

Through the scan, found two spots in "HTTP Protocol" section that may need changes:

- Protocol names (HTTP and HTTPS) should be in UPPERCASE
- The URL schema names at the first part of URL ("http://" and "https://", which will be the actual texts to be compared) should be in lowercase
- Open a PR https://github.com/spdx/license-list-XML/pull/2537 there in license-list-XML repo for people there to decide. Text in this PR is unchanged.

Also one typo found (introduced be myself during the link format conversion), will fix that.

2024-08-08 04:01 UTC, jlovejoy commented
@zvr - now I'm confused... are we keeping the matching guidelines in the license list repo? we definitely should not have them in two places!

2024-08-09 17:20 UTC, kestewart approved these changes

2024-08-09 17:24 UTC, goneall approved these changes
LGTM

2024-08-09 17:28 UTC, merged