Remove heading numbering and fix internal refs + typos
spdx/spdx-spec pull request #1107
Opened 2024-09-06 11:28 UTC by bact

Heading numbers are now generated and some existing hard-coded anchors are not updated/wrong.

- Remove unused heading anchors that based on Heading numbering (`<a name="4.1" ...>`)
- Fix document internal refs to use `#link` that are not rely on heading numbering For example:
  - `[text](#C.2.2)` -> `[text](#guideline-official-license-headers)`
- Also fix typos about relation types in SPDX Lite
  - concludedLicense -> hasConcludedLicense
  - declaredLicense -> hasDeclaredLicense

2024-09-06 13:42 UTC, bact commented
Validation failed because the redirection of RDFs are not up-to-date yet. See #1108

2024-09-06 14:35 UTC, zvr requested changes

2024-09-06 14:35 UTC, zvr commented on docs/annexes/spdx-license-expressions.md
> +*[Order of precedence and parentheses](#order-of-precedence-and-parentheses)*.
```suggestion
[Order of precedence and parentheses](#order-of-precedence-and-parentheses).
```

2024-09-07 00:01 UTC, bact commented
Suggestions merged.

2024-09-09 22:20 UTC, goneall approved these changes
LGTM

2024-09-10 16:39 UTC, bact commented
Example validation failed - Joshua acknowledged that it is a know bug in shacl2code for 3.0.1 

PR is #1117 will update the shacl2code and should resolved this.

2024-09-10 22:03 UTC, bact commented
- PR #1117 is ready. After that one got merged, we can merge this one.

2024-09-11 23:19 UTC, bact commented
I will merge this as we need the model files updated for the coming deadline. Review again and see no issues.

2024-09-11 23:19 UTC, merged