Add English as normative notes
spdx/spdx-spec pull request #1170
Opened 2024-12-18 06:15 UTC by bact

- Add "English remains the normative language in all cases" notes (addressing one todo in #1169)
- Update branch mentions to current branch names
- Move `gh-pages` branch description to "Branch structure" section
- Add `rdf/` directory description

2024-12-18 20:46 UTC, goneall requested changes
Pending agreement on how we merge translations, we may need to make a change as suggested.

2024-12-18 20:46 UTC, goneall commented on README.md
> +  Once any changes are accepted and released, the support branch will be tagged
Note that this is different from what @zvr recommended in issue #1169 where the translations will not be merged.  We could document "non-translation ..."

2025-01-05 09:41 UTC, bact commented on README.md
> +  Once any changes are accepted and released, the support branch will be tagged
The text "Additions such as translations can be added to the support branch." is from what previously was.

I will just remove the sentence as it seems like the rest of the description in the `support/x.y` bullet is sufficient.

2025-01-05 09:44 UTC, bact commented on README.md
> +  Once any changes are accepted and released, the support branch will be tagged
The sentence is now removed.

2025-01-05 17:59 UTC, goneall approved these changes
LGTM - Thanks @bact

2025-01-15 00:58 UTC, bact commented
With one approval, will merge as this documentation is an agreed [TODO](https://github.com/spdx/spdx-spec/issues/1169) from [2024-06-11 Tech call](https://github.com/spdx/meetings/blob/main/tech/2024/2024-06-11.md). Further changes can be made in another PR.

2025-01-15 00:58 UTC, merged