add some missing people
spdx/spdx-spec pull request #472
Opened 2020-09-15 21:58 UTC by jlovejoy

Alan Tse, Bradlee Edmondson, Mark Atwood

2020-09-29 18:51 UTC, silverhook commented on chapters/index.md
> +Matija Suklje,
Matija Šuklje

Sorry, I know it’s a special character, but I like it :smile_cat: 

Thank you for the mention, BTW!

2020-12-27 14:04 UTC, wieseaka approved these changes

2020-12-27 14:05 UTC, wieseaka reviewed
[]() 
Duplicate of #

2021-07-06 11:54 UTC, silverhook requested changes
Apart from the character, LGTM.

2021-09-10 21:11 UTC, kestewart approved these changes

2021-09-10 21:11 UTC, merged