Make required licensing fields optional
spdx/spdx-spec pull request #635
Opened 2022-03-10 21:58 UTC by rnjudge

Currently, licensing fields like `Concluded License`, `Declared License`
and `Copyright Text` are required for package elements. Given that we
are working to communicate security information in SPDX 2.3, this commit
proposes a change to make the fields related to [package, file, snippet]
licensing optional so those who want to use SPDX to only communicate
security information can do that without the bloat of NOASSERTION
licensing field values.

This PR specifically changes the following fields to optional:
```
Package Concluded license - 7.13
Package Declared license - 7.15
Package Copyright text - 7.17
File Concluded license - 8.5
License information in file - 8.6
File Copyright text - 8.8
Snippet Concluded license - 9.5
Snippet Copyright text - 9.8
```

Resolves #634

Signed-off-by: Rose Judge <rjudge@vmware.com>

2022-03-10 22:39 UTC, rnjudge commented
@kestewart, @tsteenbe Open question for this PR - does cardinality also need to change from `1..` to `0..` for the fields mentioned above?

@swinslow also suggested adding a comment to the effect of `If one of these fields is absent for a Package / File / Snippet, then that has the equivalent meaning of NOASSERTION.` I suggest adding this comment to each changed field for clarity but we could also put the notice somewhere more central. I'd like to nail down verbiage before updating my PR... would something like the following to be added under the "Description" section of each field work?
```
If [insert appropriate field name here] is omitted in an SPDX document, it has the equivalent value of NOASSERTION.
```

Suggestions welcome :)

2022-03-11 21:51 UTC, rnjudge commented
Hi @swinslow- I made the edits you suggested, please take a look when you have time. Hoping to review this at next Tuesday's tech call.

2022-05-10 17:06 UTC, kestewart approved these changes
Reviewed and I think we're good.

2022-05-10 17:38 UTC, swinslow approved these changes
+1 from me, thanks @rnjudge and sorry for the delay!

2022-05-17 08:49 UTC, tsteenbe requested changes
@rnjudge  Could you fix the merge conflict?

2022-05-17 16:49 UTC, kestewart approved these changes

2022-05-17 16:49 UTC, merged