Snippets support in Annex H
spdx/spdx-spec pull request #718
Opened 2022-06-14 21:52 UTC by silverhook

As discussed in https://github.com/spdx/spdx-spec/pull/464 this PR expands Annex H to include snippet-level tags in source code.

PR instead of https://github.com/spdx/spdx-spec/pull/464

2022-06-14 21:56 UTC, silverhook commented
I do not remember what the outcome on the calls was regarding how and if at all nesting of snippets should work, so in this version I completely left this part out.

AFAICR two options are possible:
1. nesting like brackets and in most markup where the closest begin and end tag belong to each other
2. no nesting, so before a new snippet begin tag is allowed, the previous snippet has to have an end tag

I’m more in favour of 1.

2022-06-14 22:33 UTC, goneall commented
> I do not remember what the outcome on the calls was regarding how and if at all nesting of snippets should work, so in this version I completely left this part out.

I recall the consensus was option 1 - nesting like brackets and in most markup where the closest begin and end tag belong to each other

2022-06-14 22:36 UTC, goneall commented
@silverhook - only comment is to mention the nesting (option 1 above).

2022-06-15 03:10 UTC, zvr requested changes

2022-06-15 03:10 UTC, zvr commented on chapters/file-tags.md
> +If certain SPDX file tags are to apply only to a certain snippet instead of the whole file, the start of such snippet should be marked with `SPDX-SnippetBegin` and its end with `SPDX-SnippetBegin`.
Ahem. Probably more useful to denote the end with `SPDX-SnippetEnd` instead with `Begin`.

2022-06-15 03:10 UTC, zvr commented on chapters/file-tags.md
> +
Add something like:

Snippets may nest, and this is denoted by having `SPDX-SnippetBegin`/`SPDX-SnippetEnd` pairs within other pairs, in the same way that parentheses nest in mathematical expressions.
In the case of nested snippets, the SPDX file tags are considered to apply to the inner-most snippet.

2022-06-15 07:13 UTC, silverhook commented on chapters/file-tags.md
> +## H.3 File Tags Within Snippets <a name="H.3"></a>
Will change it, thanks.

But chapter titles still use title case, right? (That’s where I copied the style from)

2022-06-15 07:53 UTC, zvr commented on chapters/file-tags.md
> +## H.3 File Tags Within Snippets <a name="H.3"></a>
Eh, no: `8 File information section` or `3 Terms and definitions`.
It was one of the changes when we were preparing for ISO...
`

2022-06-15 07:56 UTC, silverhook commented on chapters/file-tags.md
> +Any Snippet Information (Clause [9](snippet-information.md)) and short-form license identifiers (Annex [E](using-SPDX-short-identifiers-in-source-files.md)) tags found between begin and end tags ment
I didn’t want to mess around with the existing parts too much, but have tried to implement what you’re (reasonably!) asking for @zvr.

It feel we can simplify this by explicitly separating snippet tags from file tags. I’ll create a new PR for what I mean.

2022-06-15 09:58 UTC, silverhook commented on chapters/file-tags.md
> +Any Snippet Information (Clause [9](snippet-information.md)) and short-form license identifiers (Annex [E](using-SPDX-short-identifiers-in-source-files.md)) tags found between begin and end tags ment
A restructured version, that IMHO looks better: https://github.com/spdx/spdx-spec/pull/719

2022-06-15 09:59 UTC, silverhook commented
As an alternative to this PR, I created also https://github.com/spdx/spdx-spec/pull/719, which IMHO is better structured.

I am keeping both open so we can decide between:
- the clearer and better structured https://github.com/spdx/spdx-spec/pull/719; and
- keeping the original structure in https://github.com/spdx/spdx-spec/pull/718

2022-06-15 10:15 UTC, silverhook commented on chapters/file-tags.md
> +## H.3 File Tags Within Snippets <a name="H.3"></a>
So we should change the chapter title as well then?

2022-06-16 15:10 UTC, silverhook commented
Closing in favour of the approved #719

2022-06-16 15:10 UTC, closed without merging