Add SHA1-DC algorithm to recognized set.
spdx/spdx-spec pull request #734
Opened 2022-07-01 20:08 UTC by kestewart

From information provided by David A. Wheeler:  Git uses SHA-1DC, not SHA-1, as its default hash algorithm. This algorithm normally produces the same result as sha-1 but it tries to detect collision attacks and provides a different result then.  It's been in use since 2017, so we should add it as a valid option. 

Implementation and link to paper about it: https://github.com/cr-marcstevens/sha1collisiondetection
News article about git and hash algorithms: https://lwn.net/Articles/898522/

Also included is adding back SHA1 reference, which appears to have been accidently removed when the new algorithms were added. 

Signed-off-by: Kate Stewart <kate.stewart@att.net>

2022-07-02 16:27 UTC, goneall commented
In reading the background on this, I'm not sure this is really a different hash than SHA1.  It the definition of this a SHA1 which has passed the collision detection from the referred to github repo?  If so, I think we need to define that in the spec - otherwise it may be confusing.  It would be nice if there was a website with a description we could refer to that provide more of a definition - the repo as a reference is a bit confusing.

2022-07-02 16:32 UTC, goneall requested changes
Can we find a way to clarify this - I found it confusing as to what exactly SHA1-DC represents.

2022-07-02 16:32 UTC, goneall commented on chapters/file-information.md
> +[SHA1-DC]: https://github.com/cr-marcstevens/sha1collisiondetection
Is the intent that the SHA1-DC is a SHA1 that the SPDX creator states has passed the collision detection?  If so, I'm not sure this is really a different HASH algorithm from SHA1.

2022-07-06 13:22 UTC, kestewart commented
Based on comments from meeting on 6/5, we're going to close this for now, and revisit as an algorithm for 3.0.

2022-07-06 13:22 UTC, closed without merging