Sync the model diagrams with the model repo
spdx/spdx-spec pull request #886
Opened 2024-02-18 00:27 UTC by goneall

This updates the diagrams with the model repo after merging https://github.com/spdx/spdx-3-model/pull/643

2024-02-18 02:48 UTC, kestewart requested changes
Not sure why model-security-profile.png is included when there is a "model Secuirty.png".   Included by error?   Also file looks like Core+Software not security.

2024-02-18 02:48 UTC, kestewart commented on docs/images/model-security-profile.png
Double check,  this is looking like the core, not security.   Also, is this reducnant with model Security.png.

2024-02-18 20:43 UTC, goneall commented on docs/images/model-security-profile.png
Removed the extra image.

I noticed this too while on the plane.

The image is present in the model repo - it is stale compared to model Security.png.

BTW - The image was not used in the website or PDF.

2024-02-27 16:14 UTC, goneall commented
Resolved @kestewart feedback, merging

2024-02-27 16:14 UTC, merged