allow `and`, `or` and `with` operators
spdx/spdx-spec pull request #892
Opened 2024-03-07 13:40 UTC by xsuchy

This is follow up of discussion https://lists.spdx.org/g/spdx/message/1798 where this was found as good compromise https://lists.spdx.org/g/spdx/message/1817

And followup of https://github.com/spdx/spdx-spec/pull/876

2024-03-07 15:18 UTC, zvr requested changes

2024-03-07 15:18 UTC, zvr commented on docs/annexes/SPDX-license-expressions.md
> +  simple-expression "with" addition-expression /
please group the two versions in a single line:

```simple-expression ( "WITH" / "with" ) addition-expression```

2024-03-07 15:18 UTC, zvr commented on docs/annexes/SPDX-license-expressions.md
> +License expression operators (`AND`, `and`, `OR`, `or`, `WITH` and `with`) should be matched in a *case-sensitive* manner. I.e., variations `And`, `oR` are not allowed.
I don't think the final explanation is needed.

If we want to have it in, reword it to something like:

> manner, i.e., letters must be all upper case or all lower case.

2024-03-07 15:45 UTC, xsuchy commented
Updated.

2024-03-27 06:37 UTC, xsuchy commented
ping. @zvr can you please re-review?

2024-03-27 08:19 UTC, zvr approved these changes

2024-03-27 11:57 UTC, Conan-Kudo approved these changes

2024-04-01 16:09 UTC, goneall approved these changes
LGTM - Going ahead and merging

2024-04-01 16:19 UTC, merged