Update index.md
spdx/spdx-spec pull request #911
Opened 2024-04-14 18:41 UTC by kestewart

Add in contributors to the spec over the last year.

2024-04-14 19:24 UTC, kestewart commented
@goneall - I've added in Meret & Armin.   Let me know if you spot any others that should be added.

2024-04-14 19:40 UTC, goneall requested changes
A couple suggested addes.

Also, please add the following (Github would not allow me to make this as a suggestion):
Takashi Ninjouji

2024-04-14 19:40 UTC, goneall commented on docs/index.md
>  Jonas Oberg,
```suggestion
Jonas Oberg,
Joshua Watt,
```

2024-04-14 19:40 UTC, goneall commented on docs/index.md
>  Bradlee Edmondson,
```suggestion
Bradlee Edmondson,
Brandon Lum,
```

2024-04-14 21:57 UTC, goneall approved these changes
LGTM

2024-04-15 02:57 UTC, puerco approved these changes
LGTM :two_hearts:

2024-04-15 03:39 UTC, merged

2024-04-15 03:39 UTC, kestewart commented
Given we've got 2 +1's going ahead and merging this.