Add 3.0 and 2.3 changes to CHANGELOG.md
spdx/spdx-spec pull request #920
Opened 2024-04-16 17:45 UTC by goneall

We switched over to using the GitHub release notes on version 2.3 and later.

This adds references to the GitHub release notes in the CHANGELOG.md

Fixes #919

2024-04-19 23:21 UTC, bact requested changes

2024-04-19 23:21 UTC, bact commented on CHANGELOG.md
> +See the [v3.0 GithHub release notes](https://github.com/spdx/spdx-spec/releases/tag/v3.0) for changes.
GithHub -> GitHub

2024-04-19 23:21 UTC, bact commented on CHANGELOG.md
> +See the [v2.3 GithHub release notes](https://github.com/spdx/spdx-spec/releases/tag/v2.3) for changes.
GithHub -> GitHub

2024-04-20 20:28 UTC, goneall commented on CHANGELOG.md
> +See the [v3.0 GithHub release notes](https://github.com/spdx/spdx-spec/releases/tag/v3.0) for changes.
Update - Thanks @bact  for the catch

2024-04-20 20:46 UTC, kestewart approved these changes

2024-04-20 20:46 UTC, kestewart commented
Thanks @bact for the catch.  It looks fine to me.

2024-04-22 16:54 UTC, bact approved these changes

2024-04-22 18:01 UTC, merged