Meaning of the SPDX acronym has changed in SPDX 3.0
spdx/spdx-spec pull request #954
Opened 2024-04-30 15:43 UTC by vargenau

2024-04-30 17:47 UTC, goneall requested changes
Suggestion to add a bit of context

2024-04-30 17:47 UTC, goneall commented on docs/annexes/diffs-from-previous-editions.md
> +Starting with V3.0, SPDX means "System Package Data Exchange".
```suggestion
Starting with V3.0, the scope of SPDX has expanded beyond software and now means "System Package Data Exchange".
```

2024-05-06 17:47 UTC, bact commented
Can we also add this to the Glossary as well?

2024-07-18 13:06 UTC, vargenau commented
> Can we also add this to the Glossary as well?

I have created https://github.com/spdx/spdx-3-model/pull/801 for that.

2024-08-09 17:29 UTC, kestewart approved these changes
Thanks!  Looks good.

2024-08-09 17:33 UTC, goneall approved these changes
Resolved merge conflicts and changes look good

2024-08-09 17:38 UTC, goneall commented
Replaced with PR #1030 - could not resolve merge conflicts with this PR

2024-08-09 17:38 UTC, closed without merging