Add clarification for case-sensitivity for LicenseRef-
spdx/spdx-spec pull request #984
Opened 2024-07-09 09:36 UTC by vargenau

See https://github.com/spdx/spdx-spec/issues/981

2024-07-09 21:49 UTC, goneall approved these changes
This resolves an inconsistency in the spec.  Note that the SPDX Java tools does not currently support this clarification, however.  There is an existing issue to track updating the SPDX Java tools.

2024-07-12 04:59 UTC, lpanni approved these changes

2024-07-16 09:19 UTC, zvr requested changes
And I would also add this line to the previous paragraph (after "case insensitive.") instead of having it as a separate paragraph.

2024-07-16 09:19 UTC, zvr commented on docs/annexes/SPDX-license-expressions.md
> +So, `LicenseRef-Beerware-4.2` and `LicenseRef-beerware-4.2` are the same identifier, and `licenseref-beerware-4.2` is not a valid license identifier.
```suggestion
This means, for example, that `LicenseRef-Name` and `LicenseRef-name` should be treated as the same identifier and considered to refer to the same license, while `licenseref-name` is not a valid license identifier.
```

2024-07-16 17:28 UTC, vargenau commented
@zvr 
Merging is blocked by DCO.
Should I do something?

2024-07-16 18:02 UTC, bact commented
@vargenau  DCO requires you to signed-off the commit again (for every commits).

2024-07-17 07:42 UTC, vargenau commented
> @vargenau DCO requires you to signed-off the commit again (for every commits).

Is it me or @zvr as he made a change to my commit?

2024-07-17 15:36 UTC, bact commented
Anyone who actually make the commit.
(in this case, zvr only suggested the change but not actually commit the change himself).

Try this to rebase https://github.com/spdx/spdx-spec/pull/984/checks?check_run_id=27520863733
(not always successful, to my experience, as there can be some conflicts that can't be rebased. but still worth a try)

2024-07-18 10:46 UTC, vargenau commented
> Anyone who actually make the commit. (in this case, zvr only suggested the change but not actually commit the change himself).
> 
> Try this to rebase https://github.com/spdx/spdx-spec/pull/984/checks?check_run_id=27520863733 (not always successful, to my experience, as there can be some conflicts that can't be rebased. but still worth a try)

Thank you @bact for your help. It's done. 

Please merge.

2024-07-30 04:28 UTC, goneall commented
It looks like the requested change from @zvr has been made, going ahead and merging.

2024-07-30 04:28 UTC, merged