Correct Annex list
spdx/spdx-spec pull request #992
Opened 2024-07-16 09:43 UTC by zvr

A number of informative documents were copied from being annexes of the spec to their own repository https://github.com/spdx/using.

This PR removes them from the spec repo, and renumbers the rest of the annexes.
It also updates the mkdocs configuration to use this new list.

Signed-off-by: Alexios Zavras <github@zvr.gr>

2024-07-16 16:07 UTC, rnjudge commented
Discussed in July 16th tech call. LGTM.

2024-07-20 19:03 UTC, goneall approved these changes
LGTM

2024-07-30 04:30 UTC, goneall commented
@zvr - can you resolve the merge conflicts - then I will merge based on the comments above

2024-07-30 22:43 UTC, bact requested changes
Use full word

(same as in [v2.3](https://spdx.github.io/spdx-spec/v2.3/diffs-from-previous-editions/))

2024-07-30 22:43 UTC, bact commented on mkdocs.yml
> +  - 'A: Diffs from Previous Editions': annexes/diffs-from-previous-editions.md
'A: Diffs' -> 'A: Differences'

2024-07-30 22:48 UTC, bact requested changes

2024-07-30 22:48 UTC, bact commented on mkdocs.yml
> +  - 'E: Package URL specification': annexes/pkg-url-specification.md
Some annex headings capitalize the first word and lowercase the rest, while the other capitalize (almost) every words. Should stick to one style.

(Exceptions can be made for proper nouns/names)

2024-08-01 14:51 UTC, bact commented on mkdocs.yml
> +  - 'E: Package URL specification': annexes/pkg-url-specification.md
I'm taking the titles from the Annex files themselves:

```
  - 'A: Differences from previous editions': annexes/diffs-from-previous-editions.md
  - 'B: RDF object model and identifier syntax': annexes/RDF-object-model-and-identifier-syntax.md
  - 'C: SPDX license expressions': annexes/SPDX-license-expressions.md
  - 'D: License matching guidelines and templates': annexes/license-matching-guidelines-and-templates.md
  - 'E: Package URL specification v1': annexes/pkg-url-specification.md
```

2024-08-05 10:03 UTC, bact commented
@bobmartin3000 what is the prefer capitalization style for title and section names please?

We have quite a mix currently. For example:

- [2.1 Normative References](https://github.com/spdx/spdx-spec/pull/1006/files)
- [3 Terms and Definitions](https://github.com/spdx/spdx-spec/pull/1004/files)
- [Annex A: Differences from previous editions (Informative)](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/diffs-from-previous-editions.md)
- [Annex B: RDF object model and identifier syntax (Normative)](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/RDF-object-model-and-identifier-syntax.md)
- [Annex E: Package URL specification v1 (Normative)](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/pkg-url-specification.md)
- [Annex F: History, Motivation and Rational (Informative)](https://github.com/spdx/spdx-spec/pull/1008/files)

2024-08-05 13:20 UTC, bobmartin3000 commented
I would capitalize main words like the first two and last one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Arthit Suriyawongkul ***@***.***>
Sent: Monday, August 5, 2024 6:04:05 AM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Correct Annex list (PR #992)

@bobmartin3000 what is the prefer capitalization style for title and section names please? We have quite a mix currently. For example: 2. 1 Normative References 3 Terms and Definitions Annex A: Differences from previous editions (Informative)


@bobmartin3000<https://github.com/bobmartin3000> what is the prefer capitalization style for title and section names please?

We have quite a mix currently. For example:

  *   2.1 Normative References<https://github.com/spdx/spdx-spec/pull/1006/files>
  *   3 Terms and Definitions<https://github.com/spdx/spdx-spec/pull/1004/files>
  *   Annex A: Differences from previous editions (Informative)<https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/diffs-from-previous-editions.md>
  *   Annex B: RDF object model and identifier syntax (Normative)<https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/RDF-object-model-and-identifier-syntax.md>
  *   Annex E: Package URL specification v1 (Normative)<https://github.com/spdx/spdx-spec/blob/development/v3.0.1/docs/annexes/pkg-url-specification.md>
  *   Annex F: History, Motivation and Rational (Informative)<https://github.com/spdx/spdx-spec/pull/1008/files>

—
Reply to this email directly, view it on GitHub<https://github.com/spdx/spdx-spec/pull/992#issuecomment-2268689003>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUYBD7DWF55THJTMMVZXHD3ZP5EZLAVCNFSM6AAAAABK6GUWGKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRYGY4DSMBQGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-08-05 14:06 UTC, bact commented
> I would capitalize main words like the first two and last one Get Outlook for iOS<https://aka.ms/o0ukef>

Thank you @bobmartin3000. Then if everyone agree, I will update headings in mkdocs.yml and in actual files (chapters/sections/annexes) to consistently match that style.

2024-08-10 14:44 UTC, kestewart commented
@zvr, @bact - looks like we've got some conflicts now that need to be resolved -   can you take a pass at sorting them?

2024-08-10 16:55 UTC, kestewart approved these changes

2024-08-10 17:17 UTC, goneall commented
@zvr - Could you resolve the merge conflicts?  It looks like most of them are referencing deleted files, so it shouldn't be too challenging.

We put in a separate issue for the Title casing #1041 - so we can merge this and fix the titles later.  Once the merge conflicts are resolved, we can merge.

2024-08-10 17:41 UTC, goneall commented
This will be replaced by a new PR on 11 August

2024-08-10 17:41 UTC, closed without merging