Publish 3.0.1 as v3.0.1-draft
spdx/spdx-spec pull request #995
Opened 2024-07-18 09:09 UTC by bact

### What has happened?

- From PR #950, v3.0.1 was failed to published with an alias "latest"
  - See the error message: https://github.com/spdx/spdx-spec/actions/runs/9986239266/job/27598397125
- This is because v2.3 still occupied the "latest" alias.
- In the command `mike deploy IDENTIFIER ALIAS` (as in `mike deploy v3.0.1 latest`):
  - Be default, `mike` will prevent the alias setting if the given identifier (`v3.0.1`) is different from the identifier that currently occupied the alias (`v2.3`)
  - `v3.0.1` != `v2.3`
  - This can be override by `-u` option.
    - `mike deploy -u IDENTIFIER ALIAS`

### What this PR do?

Loosely applying steps 5, 7, and 8 in https://github.com/spdx/spdx-spec/pull/950#issuecomment-2096536032 but changing the alias `latest` to `v3.0.1-draft` for the moment while 3.0.1 is still in development.

- in .github/workflows/publish_v3.yml:
  - Set `-u` option for `mike deploy` to publish `v3.0` as `latest`
    -  `run: mike deploy -u -b gh-pages -p v3.0.1 latest`
  - Also update `actions/checkout` to v4 to prevent build warning of Node.js deprecation

This will effectively publish `v3.0.1-draft`, using `development/v3.0.1` of `spdx-spec` and `main` of `spdx-model`.

After v3.0.1 is released, another PR can be made to publish `v3.0.1` using `development/v3.0.1` of `spdx-spec` and `3.0.1` of `spdx-model`.

2024-07-24 16:20 UTC, zvr requested changes

2024-07-24 16:20 UTC, zvr commented on mkdocs.yml
> +copyright: DRAFT version generated from (main) model by (main) parser
```suggestion
copyright: DRAFT -- v3.0.1 -- DRAFT
```

2024-07-24 16:24 UTC, zvr approved these changes

2024-07-24 16:29 UTC, bact commented
Have to copy list of model files (from `mkdocs-files.yml`) to `mkdocs.yml`'s `nav` section

2024-07-24 20:31 UTC, goneall commented
@puerco - Should we use commits for the actions rather than tags?

2024-07-24 22:11 UTC, bact commented
Can change to

```yaml
uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
```

2024-07-25 02:04 UTC, goneall commented
> Can change to
> 
> ```yaml
> uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
> ```

Thanks @bact - this should resolve the possible security issue if the tag is changed.

2024-07-26 07:33 UTC, bact commented
@zvr `publish_v3.yml` publication workflow is now using the actual list of model entries generated by spec-parser. See lines 56-69.

Note that I have modify the PR validation workflow `validate_pull_request.yml` to do the same (using the generated list of model entries). This is necessary to have this PR pass all the checks.

2024-07-26 10:04 UTC, zvr commented
I think the default shown should be the one we're working on, but this can be decided and changed later.
Waiting for another approval to commit this.

2024-07-26 17:58 UTC, bact commented
Agree. Let's have this published first and we can start seeing updated contents and formats. Then made any necessary changes afterwards.

2024-07-30 04:31 UTC, goneall approved these changes
LGTM

2024-07-30 04:36 UTC, merged

2024-07-30 09:13 UTC, bact commented
Thank you. Content from `development/v3.0.1` is now published at https://spdx.github.io/spdx-spec/v3.0.1-draft/